// ─── Permissions ───────────────────────────────────────────────────
export interface RoomPermissions {
  /** Whether viewers can play/pause/seek (default: true) */
  viewersCanControl: boolean;
  /** Whether viewers can send chat messages (default: true) */
  viewersCanChat: boolean;
}

// ─── User ──────────────────────────────────────────────────────────
export interface User {
  /** Unique session ID (generated on connect) */
  id: string;
  /** Display name shown in the room */
  displayName: string;
  /** Optional avatar URL or gravatar hash */
  avatar?: string;
  /** Whether this user created the room */
  isHost: boolean;
  /** Persistent device/browser ID (generated by client) */
  peerId?: string;
  /** Connection status */
  connectionStatus?: "online" | "away";
  /** User's current local video timestamp (seconds) */
  videoTimestamp?: number;
}

// ─── Room ──────────────────────────────────────────────────────────
export interface RoomState {
  /** Deterministic room name (used as DO ID) */
  id: string;
  /** Human-readable room name */
  name: string;
  /** Connected users */
  users: User[];
  /** Current playback timestamp in seconds */
  currentTime: number;
  /** Whether playback is paused */
  paused: boolean;
  /** Playback rate (1 = normal) */
  playbackRate: number;
  /** Room permissions */
  permissions: RoomPermissions;
}

// ─── WebSocket: Client → Server ────────────────────────────────────

export type WSClientMessage =
  | {
      type: "join";
      user: Omit<User, "id"> & { peerId: string };
      password?: string;
    }
  | { type: "leave" }
  | { type: "play"; currentTime: number }
  | { type: "pause"; currentTime: number }
  | { type: "seek"; currentTime: number }
  | { type: "chat"; message: string }
  | { type: "sync-request" }
  | { type: "playback-rate"; rate: number }
  | { type: "time-update"; currentTime: number }
  | { type: "kick"; userId: string }
  | {
      type: "update-permissions";
      permissions: Partial<RoomPermissions>;
    };

// ─── WebSocket: Server → Client ────────────────────────────────────

export type WSServerMessage =
  | { type: "user-joined"; user: User }
  | { type: "user-left"; userId: string }
  | { type: "play"; currentTime: number; userId: string }
  | { type: "pause"; currentTime: number; userId: string }
  | { type: "seek"; currentTime: number; userId: string }
  | { type: "chat"; message: string; userId: string; displayName: string }
  | { type: "sync"; room: RoomState }
  | { type: "error"; code: string; message: string }
  | { type: "room-state"; room: RoomState; yourUserId: string }
  | { type: "playback-rate"; rate: number; userId: string }
  | { type: "kicked"; reason: string }
  | { type: "permissions-updated"; permissions: RoomPermissions }
  | { type: "user-time-update"; userId: string; currentTime: number };

// ─── REST API ──────────────────────────────────────────────────────

export interface CreateRoomRequest {
  name: string;
  password?: string;
  /** Initial host's client-generated persistent ID */
  hostPeerId?: string;
}

export interface CreateRoomResponse {
  roomId: string;
  name: string;
}

export interface CreateRoomConflictResponse {
  error: "ROOM_EXISTS";
  message: string;
}

export interface RoomStateResponse {
  room: RoomState;
}

export interface RoomExistsResponse {
  exists: boolean;
}

export interface ApiErrorResponse {
  error: string;
}
