/**
 * vinext-supported public modules whose declarations cannot be vendored
 * directly from the installed Next.js package, plus vinext-specific extensions.
 * The primary shared surface is generated by scripts/sync-next-types.mjs instead.
 */
// oxlint-disable-next-line typescript/triple-slash-reference
/// <reference path="./next-shims-missing-modules-vinext.d.ts" />

// Next.js publishes this entrypoint with an unresolved type-only import from
// its private, compiled copy of web-vitals. Keep the public function signature
// here so consuming projects do not need either next or web-vitals installed.
declare module "next/web-vitals" {
  export function useReportWebVitals(
    reportWebVitalsFn: (metric: {
      name: "CLS" | "FCP" | "FID" | "INP" | "LCP" | "TTFB";
      value: number;
      rating: "good" | "needs-improvement" | "poor";
      delta: number;
      id: string;
      entries: PerformanceEntry[];
      navigationType:
        | "navigate"
        | "reload"
        | "back-forward"
        | "back-forward-cache"
        | "prerender"
        | "restore";
    }) => void,
  ): void;
}

declare module "next/navigation" {
  export function useRouter(): import("@vinext/types/next/upstream/dist/shared/lib/app-router-context.shared-runtime").AppRouterInstance & {
    bfcacheId: string;
  };
}

// Next.js's generated typed-route declarations import these private module
// paths. Keep them resolvable when vinext supplies the vendored declarations
// instead of an installed `next` package.
declare module "next/types.js" {
  export * from "@vinext/types/next/upstream/types";
  export { default } from "@vinext/types/next/upstream/types";
}

declare module "next/dist/client/link.js" {
  export * from "@vinext/types/next/upstream/dist/client/link";
  export { default } from "@vinext/types/next/upstream/dist/client/link";
}

declare module "next/dist/client/components/navigation.js" {
  export * from "@vinext/types/next/upstream/dist/client/components/navigation";
}

declare module "next/dist/shared/lib/app-router-context.shared-runtime.js" {
  export * from "@vinext/types/next/upstream/dist/shared/lib/app-router-context.shared-runtime";
}

declare module "next/dist/client/components/redirect-error.js" {
  export * from "@vinext/types/next/upstream/dist/client/components/redirect-error";
}

declare module "next/dist/client/form.js" {
  export * from "@vinext/types/next/upstream/dist/client/form";
  export { default } from "@vinext/types/next/upstream/dist/client/form";
}
