import fs from "node:fs/promises";
import path from "node:path";
import { appRouteGraph } from "./routing/app-router.js";
import { patternToNextFormat } from "./routing/route-validation.js";
import { decodeRouteSegment } from "./routing/utils.js";

type GenerateRouteTypesOptions = {
  root: string;
  appDir?: string | null;
  pageExtensions?: readonly string[];
};

type ParamShape = Map<string, "string" | "string[]" | "string[]?">;

export async function generateRouteTypes(options: GenerateRouteTypesOptions): Promise<string> {
  const root = path.resolve(options.root);
  const appDir = options.appDir ? path.resolve(options.appDir) : await findAppDir(root);
  const outPath = path.join(root, ".next", "types", "routes.d.ts");

  const content = appDir
    ? renderRouteTypes(await collectRouteTypeModel(appDir, options.pageExtensions))
    : renderRouteTypes(emptyRouteTypeModel());

  await fs.mkdir(path.dirname(outPath), { recursive: true });
  await fs.writeFile(outPath, content, "utf-8");
  return outPath;
}

type RouteTypeModel = {
  pageRoutes: string[];
  layoutRoutes: string[];
  routeHandlerRoutes: string[];
  params: Map<string, ParamShape>;
  layoutSlots: Map<string, string[]>;
};

function emptyRouteTypeModel(): RouteTypeModel {
  return {
    pageRoutes: [],
    layoutRoutes: [],
    routeHandlerRoutes: [],
    params: new Map(),
    layoutSlots: new Map(),
  };
}

async function collectRouteTypeModel(
  appDir: string,
  pageExtensions?: readonly string[],
): Promise<RouteTypeModel> {
  const graph = await appRouteGraph(appDir, pageExtensions);
  const model = emptyRouteTypeModel();
  const segmentGraph = graph.routeManifest.segmentGraph;

  for (const route of segmentGraph.pages.values()) {
    const routeEntry = segmentGraph.routes.get(route.routeId);
    addRoute(
      model.pageRoutes,
      model.params,
      patternToNextFormat(route.pattern),
      paramsForPatternParts(routeEntry?.patternParts ?? []),
    );
  }

  for (const route of segmentGraph.routeHandlers.values()) {
    const routeEntry = segmentGraph.routes.get(route.routeId);
    addRoute(
      model.routeHandlerRoutes,
      model.params,
      patternToNextFormat(route.pattern),
      paramsForPatternParts(routeEntry?.patternParts ?? []),
    );
  }

  for (const layout of segmentGraph.layouts.values()) {
    const route = treePathToRouteLiteral(layout.treePath);
    addRoute(model.layoutRoutes, model.params, route, paramsForRouteLiteral(route));
  }

  for (const slot of segmentGraph.slots.values()) {
    const layoutRoute = treePathToRouteLiteral(slot.ownerTreePath);
    const slots = model.layoutSlots.get(layoutRoute) ?? [];
    if (!slots.includes(slot.name)) {
      slots.push(slot.name);
      slots.sort(compareStrings);
    }
    model.layoutSlots.set(layoutRoute, slots);
  }

  return model;
}

async function findAppDir(root: string): Promise<string | null> {
  for (const rel of ["app", path.join("src", "app")]) {
    const candidate = path.join(root, rel);
    try {
      const stat = await fs.stat(candidate);
      if (stat.isDirectory()) return candidate;
    } catch {
      // Try the next conventional app directory.
    }
  }
  return null;
}

function renderRouteTypes(model: RouteTypeModel): string {
  const allRoutes = uniqueSorted([
    ...model.pageRoutes,
    ...model.layoutRoutes,
    ...model.routeHandlerRoutes,
  ]);

  return `// This file is generated by vinext. Do not edit.
import type * as React from "react";

declare global {
  type PageProps<Route extends VinextRouteTypes.PageRoute = VinextRouteTypes.PageRoute> = {
    params: Promise<VinextRouteTypes.ParamMap[Route]>;
    searchParams: Promise<Record<string, string | string[] | undefined>>;
  };

  type LayoutProps<Route extends VinextRouteTypes.LayoutRoute = VinextRouteTypes.LayoutRoute> = {
    params: Promise<VinextRouteTypes.ParamMap[Route]>;
    children: React.ReactNode;
  } & {
    [K in VinextRouteTypes.LayoutSlotMap[Route]]: React.ReactNode;
  };

  type RouteContext<Route extends VinextRouteTypes.RouteHandlerRoute = VinextRouteTypes.RouteHandlerRoute> = {
    params: Promise<VinextRouteTypes.ParamMap[Route]>;
  };
}

declare namespace VinextRouteTypes {
  type PageRoute = ${routeUnion(model.pageRoutes)};
  type LayoutRoute = ${routeUnion(model.layoutRoutes)};
  type RouteHandlerRoute = ${routeUnion(model.routeHandlerRoutes)};
  type AppRoute = ${routeUnion(allRoutes)};

  interface ParamMap {
${renderParamMap(allRoutes, model.params)}
  }

  interface LayoutSlotMap {
${renderLayoutSlotMap(model.layoutRoutes, model.layoutSlots)}
  }
}

export {};
`;
}

function renderParamMap(
  routes: readonly string[],
  params: ReadonlyMap<string, ParamShape>,
): string {
  if (routes.length === 0) return "    [route: string]: {};\n";

  return routes
    .map((route) => `    ${quote(route)}: ${renderParamShape(params.get(route) ?? new Map())};`)
    .join("\n");
}

function renderParamShape(params: ParamShape): string {
  if (params.size === 0) return "{}";

  const fields = Array.from(params.entries())
    .sort(([left], [right]) => compareStrings(left, right))
    .map(([name, kind]) => {
      const optional = kind === "string[]?";
      const valueType = optional ? "string[]" : kind;
      return `${propertyName(name)}${optional ? "?" : ""}: ${valueType};`;
    });

  return `{ ${fields.join(" ")} }`;
}

function renderLayoutSlotMap(
  layoutRoutes: readonly string[],
  layoutSlots: ReadonlyMap<string, readonly string[]>,
): string {
  if (layoutRoutes.length === 0) return "    [route: string]: never;\n";

  return layoutRoutes
    .map((route) => {
      const slots = layoutSlots.get(route) ?? [];
      return `    ${quote(route)}: ${routeUnion(slots)};`;
    })
    .join("\n");
}

function paramsForRouteLiteral(route: string): ParamShape {
  const params: ParamShape = new Map();
  for (const segment of route.split("/")) {
    const optionalCatchAll = segment.match(/^\[\[\.\.\.([^\]]+)\]\]$/);
    if (optionalCatchAll) {
      params.set(optionalCatchAll[1], "string[]?");
      continue;
    }

    const catchAll = segment.match(/^\[\.\.\.([^\]]+)\]$/);
    if (catchAll) {
      params.set(catchAll[1], "string[]");
      continue;
    }

    const dynamic = segment.match(/^\[([^\]]+)\]$/);
    if (dynamic) {
      params.set(dynamic[1], "string");
    }
  }
  return params;
}

function paramsForPatternParts(patternParts: readonly string[]): ParamShape {
  const params: ParamShape = new Map();
  for (const part of patternParts) {
    if (!part.startsWith(":")) continue;

    if (part.endsWith("+")) {
      params.set(part.slice(1, -1), "string[]");
    } else if (part.endsWith("*")) {
      params.set(part.slice(1, -1), "string[]?");
    } else {
      params.set(part.slice(1), "string");
    }
  }
  return params;
}

function treePathToRouteLiteral(treePath: string): string {
  if (treePath === "/") return "/";

  const segments = treePath
    .split("/")
    .filter(Boolean)
    .filter((segment) => !isInvisibleSegment(segment))
    .map((segment) => decodeRouteSegment(segment));
  return segments.length === 0 ? "/" : `/${segments.join("/")}`;
}

function isInvisibleSegment(segment: string): boolean {
  return (
    segment === "." || (segment.startsWith("(") && segment.endsWith(")")) || segment.startsWith("@")
  );
}

function addRoute(
  routes: string[],
  params: Map<string, ParamShape>,
  route: string,
  paramShape: ParamShape,
): void {
  if (!routes.includes(route)) {
    routes.push(route);
    routes.sort(compareStrings);
  }
  params.set(route, paramShape);
}

function uniqueSorted(values: readonly string[]): string[] {
  return Array.from(new Set(values)).sort(compareStrings);
}

function routeUnion(routes: readonly string[]): string {
  if (routes.length === 0) return "never";
  return routes.map(quote).join(" | ");
}

function propertyName(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : quote(name);
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function compareStrings(left: string, right: string): number {
  if (left < right) return -1;
  if (left > right) return 1;
  return 0;
}
