/**
 * Type shim for the virtual image-loader module generated by vinext at build
 * time from `images.loaderFile` / `images.loader` in next.config.
 *
 * The default export is the user's image loader, or `undefined` when nothing is
 * configured — in which case the `next/image` shim falls back to its built-in
 * `/_next/image` loader. See `image/image-loader-virtual.ts` for the generator.
 *
 * This must stay a *script* (no top-level import/export) so `declare module` is
 * an ambient declaration. The same block inside `global.d.ts` would be parsed as
 * a module augmentation and silently fail to apply, which is why the virtual
 * imports declared there still need `@ts-expect-error` at their use sites.
 */
declare module "virtual:vinext-image-loader" {
  const imageLoader:
    | ((props: { src: string; width: number; quality?: number }) => string)
    | undefined;
  export default imageLoader;

  /**
   * True when `images.loader` is `"custom"` with no `images.loaderFile`: the
   * default export then reports that each `<Image>` must pass its own `loader`
   * prop rather than generating URLs.
   */
  export const requiresLoaderProp: boolean;
}
