/**
 * Type shim for the virtual cache-adapters module generated by vinext at build
 * time from the `cache` option in the vinext() plugin config.
 *
 * `registerConfiguredCacheAdapters(env)` registers the configured data / CDN
 * cache adapters on first call and is a no-op when nothing is configured. The
 * server entries call it on each request; see `cache/cache-adapters-virtual.ts`
 * for the generator.
 */
declare module "virtual:vinext-cache-adapters" {
  export function registerConfiguredCacheAdapters(env?: Record<string, unknown>): void;
}
