/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import {
  handleImageOptimization,
  DEFAULT_DEVICE_SIZES,
  DEFAULT_IMAGE_SIZES,
  isImageOptimizationPath,
} from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";

type Env = {
  ASSETS: Fetcher;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
  DB: D1Database;
  VINEXT_KV_CACHE: KVNamespace;
  PERFORMANCE_PROFILES: R2Bucket;
  COMPAT_INGEST_SECRET?: string;
};

type ExecutionContext = {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
};

async function safeEqual(a: string, b: string): Promise<boolean> {
  const encoder = new TextEncoder();
  const [left, right] = await Promise.all([
    crypto.subtle.digest("SHA-256", encoder.encode(a)),
    crypto.subtle.digest("SHA-256", encoder.encode(b)),
  ]);
  const leftBytes = new Uint8Array(left);
  const rightBytes = new Uint8Array(right);
  let difference = 0;
  for (let index = 0; index < leftBytes.length; index++) {
    difference |= leftBytes[index] ^ rightBytes[index];
  }
  return difference === 0;
}

async function uploadPerformanceProfile(request: Request, env: Env): Promise<Response> {
  const secret = request.headers.get("x-compat-secret") ?? "";
  if (
    !env.COMPAT_INGEST_SECRET ||
    !secret ||
    !(await safeEqual(secret, env.COMPAT_INGEST_SECRET))
  ) {
    return new Response("Unauthorized", { status: 401 });
  }
  const runKind = request.headers.get("x-performance-run-kind");
  const commitSha = request.headers.get("x-performance-commit-sha");
  const executionId = request.headers.get("x-performance-execution-id");
  const benchmarkId = request.headers.get("x-performance-benchmark-id");
  if (
    (runKind !== "main" && runKind !== "pull_request") ||
    !commitSha?.match(/^[0-9a-f]{40}$/i) ||
    !executionId ||
    !benchmarkId ||
    !request.body
  ) {
    return new Response("Invalid performance profile metadata", { status: 400 });
  }
  const key = `profiles/${runKind}/${commitSha.toLowerCase()}/${encodeURIComponent(executionId)}/${crypto.randomUUID()}/${encodeURIComponent(benchmarkId)}.json.gz`;
  await env.PERFORMANCE_PROFILES.put(key, request.body, {
    httpMetadata: { contentType: "application/json", contentEncoding: "gzip" },
    customMetadata: { benchmarkId, commitSha: commitSha.toLowerCase(), runKind },
  });
  return Response.json({ key }, { status: 201 });
}

// Image security config. SVG sources with .svg extension auto-skip the
// optimization endpoint on the client side (served directly, no proxy).
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below:
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    if (request.method === "PUT" && url.pathname === "/api/benchmarks/profile-upload") {
      return uploadPerformanceProfile(request, env);
    }

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (isImageOptimizationPath(url.pathname)) {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(
        request,
        {
          fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
          transformImage: async (body, { width, format, quality }) => {
            const result = await env.IMAGES.input(body)
              .transform(width > 0 ? { width } : {})
              .output({ format, quality });
            return result.response();
          },
        },
        allowedWidths,
      );
    }

    // Delegate everything else to vinext, forwarding ctx so that
    // ctx.waitUntil() is available to background cache writes and
    // other deferred work via getRequestExecutionContext().
    return handler.fetch(request, env, ctx);
  },
};
